### ISSUE TITLE
Some minor usage and development problems

### ISSUE THREAD

**Issue by mamal72** [mojtaba-asadollahzade/jquery-persian-event-calendar#1]
Hey. I just stumbleuponed here and have 2 suggestions for this repo!

1. Push normal/unminified version of your code to your Github repo.
1. Make using this library easier (no need for an HTML structure maybe) and publish your package to a package manager like [NPM](https://www.npmjs.com).

**Comment by mojtaba-asadollahzadeh** [comment]
@mamal72 
Hey, thanks for your suggestion.
I'm a little busy nowadays, but surely I will push unminified version and package manager soon.
thanks for your comment.
